disabled_rules: #rules identifiers to exclude from running
  - line_length
  - control_statement
  - todo
  - nesting

identifier_name:
  allowed_symbols: "_"
  min_length: 1

excluded:
  - Pods

file_length:
  warning: 1000
  error: 1000

function_body_length:
  warning: 100
  error: 200

function_parameter_count:
  warning: 7
  error: 10

type_body_length:
  warning: 300
  error: 300
